Hello World
Requirement already satisfied: pytest in /usr/local/lib/python3.10/dist-packages (8.3.3)
Requirement already satisfied: einops in /usr/local/lib/python3.10/dist-packages (0.8.0)
Requirement already satisfied: tomli>=1 in /usr/local/lib/python3.10/dist-packages (from pytest) (2.1.0)
Requirement already satisfied: iniconfig in /usr/local/lib/python3.10/dist-packages (from pytest) (2.0.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /usr/local/lib/python3.10/dist-packages (from pytest) (1.2.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from pytest) (24.2)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.10/dist-packages (from pytest) (1.5.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
theory_cuda_home = '/usr/local/cuda', os.path.exists(theory_cuda_home) = True
cpp_extension.CUDA_HOME = '/usr/local/cuda'
cpp_extension._find_cuda_home() = '/usr/local/cuda'
cpp_extension.CUDA_HOME = '/usr/local/cuda'


torch.__version__  = 2.5.1+cu124


Traceback (most recent call last):
  File "/tmp/telerun-execute/155f9172-d2b3-4ab3-852c-b6c076b4f8e1/fast-hadamard-transform/setup.py", line 116, in <module>
    _, bare_metal_version = get_cuda_bare_metal_version(CUDA_HOME)
  File "/tmp/telerun-execute/155f9172-d2b3-4ab3-852c-b6c076b4f8e1/fast-hadamard-transform/setup.py", line 78, in get_cuda_bare_metal_version
    raw_output = subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/cuda/bin/nvcc'
Finished install
Traceback (most recent call last):
  File "/tmp/telerun-execute/155f9172-d2b3-4ab3-852c-b6c076b4f8e1/fast-hadamard-transform/tests/test_fast_hadamard_transform.py", line 10, in <module>
    from fast_hadamard_transform.fast_hadamard_transform_interface import hadamard_transform, hadamard_transform_ref
ModuleNotFoundError: No module named 'fast_hadamard_transform'
